# Site settings
title: Clumsy Blog
email: lisihan969@gmail.com
description: >
  Talk is cheap. Show me the code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.clumsylee.me" # the base hostname & protocol for your site
github_username:  ThomasLee969

# Build settings
kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
